Try skipping the redis setup

diff --git a/start b/start
--- a/start
+++ b/start
@@ -81,18 +81,18 @@ if [ -n "$MEMCACHED_HOST" ] ; then
     >&2 echo "memcached is no longer supported, please configure redis"
 fi
 
-echo "configuring redis..."
-# Wait for redis
-TIMEOUT=0
-until run_weblate shell -c 'from django.core.cache import cache; cache.has_key("ping")' > /dev/null ; do
-    >&2 echo "redis is unavailable - waiting $((30 - $TIMEOUT))"
-    TIMEOUT=$(($TIMEOUT + 1))
-    if [ $TIMEOUT -gt 30 ] ; then
-        run_weblate shell -c 'from django.core.cache import cache; cache.has_key("ping")'
-        fail_dep redis
-    fi
-    sleep 1
-done
+#echo "configuring redis..."
+## Wait for redis
+#TIMEOUT=0
+#until run_weblate shell -c 'from django.core.cache import cache; cache.has_key("ping")' > /dev/null ; do
+#    >&2 echo "redis is unavailable - waiting $((30 - $TIMEOUT))"
+#    TIMEOUT=$(($TIMEOUT + 1))
+#    if [ $TIMEOUT -gt 30 ] ; then
+#        run_weblate shell -c 'from django.core.cache import cache; cache.has_key("ping")'
+#        fail_dep redis
+#    fi
+#    sleep 1
+#done
 
 echo "setting up postgres vars..."
 if [ -z "$POSTGRES_HOST" ] ; then
